# Generated by Django 4.2 on 2023-09-01 16:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublicScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="공용 스크립트 이름")),
                (
                    "description",
                    models.TextField(
                        help_text="스크립트를 ChatGPT에게 전했을 때 효과, 이후 사용법 등 설명",
                        verbose_name="공용 스크립트 설명서",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                10, "최대 10개의 스크립트까지 가능합니다."
                            )
                        ],
                        verbose_name="스크립트 순번",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="ChatGPT에게 전달할 스크립트", verbose_name="스크립트"
                    ),
                ),
                (
                    "public_script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scripts",
                        to="public_scripts.publicscript",
                    ),
                ),
            ],
        ),
    ]
