version: "3.8"
services:
  django:
    container_name: django
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    env_file:
      - ./backend/.env
