version: "3.8"
services:
  django:
    container_name: django
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    env_file:
      - ./backend/.env

  nginx:
    container_name: nginx
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - django
