# Generated by Django 4.2 on 2023-08-13 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name="RefBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RefData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SystemInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(default="No Description", max_length=50),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ko", "Korean")], max_length=2
                    ),
                ),
                ("major", models.CharField(default=None, max_length=20)),
                (
                    "understanding_level",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="대학교 기준입니다. 1~5학년을 선택해주세요"
                            ),
                            django.core.validators.MaxValueValidator(
                                5, "대학교 기준입니다. 1~5학년을 선택해주세요"
                            ),
                        ]
                    ),
                ),
                ("only_use_reference_data", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
