# Generated by Django 4.2 on 2023-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpt_sys_infos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systeminfo",
            name="description",
            field=models.CharField(default="No Description", max_length=50),
        ),
    ]
