# Generated by Django 4.2 on 2023-08-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpt_sys_infos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systeminfo",
            name="major",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
