# Generated by Django 4.2 on 2023-08-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpt_sys_infos", "0002_systeminfo_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="text",
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="systeminfo",
            name="major",
            field=models.CharField(default=None, max_length=20),
        ),
    ]
