# Generated by Django 4.2 on 2023-08-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatrooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="category",
            field=models.CharField(
                choices=[("general", "일반적인 질문"), ("equation", "수식 풀이")],
                default="general",
                max_length=20,
            ),
        ),
    ]
