# Generated by Django 4.2 on 2023-08-16 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gpt_sys_infos", "0004_systeminfo_data_sequence"),
        ("chatrooms", "0002_chatroom_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="system_info",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="system_info",
                to="gpt_sys_infos.systeminfo",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
