# Generated by Django 4.2 on 2023-08-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gpt_sys_infos", "0004_systeminfo_data_sequence"),
        ("chatrooms", "0004_rename_text_message_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="system_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="system_info",
                to="gpt_sys_infos.systeminfo",
            ),
        ),
    ]
