# Generated by Django 4.2 on 2023-09-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dialogues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialoguecontent",
            name="number",
            field=models.PositiveSmallIntegerField(verbose_name="dialogue 정렬 기준"),
        ),
        migrations.AlterField(
            model_name="dialoguecontent",
            name="text",
            field=models.TextField(verbose_name="dialogue 내용"),
        ),
    ]
