# Generated by Django 4.2 on 2023-08-12 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refbook",
            name="system_info",
        ),
        migrations.RemoveField(
            model_name="refdata",
            name="system_info",
        ),
        migrations.RemoveField(
            model_name="systeminfo",
            name="user",
        ),
        migrations.DeleteModel(
            name="Content",
        ),
        migrations.DeleteModel(
            name="RefBook",
        ),
        migrations.DeleteModel(
            name="RefData",
        ),
        migrations.DeleteModel(
            name="SystemInfo",
        ),
    ]
