# Generated by Django 4.2 on 2023-09-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="using_token",
            field=models.PositiveIntegerField(
                default=0,
                help_text="실질적으로 대화형 GPT 서비스를 직접 사용할 때 사용합니다.",
                verbose_name="사용한 토큰량",
            ),
        ),
    ]
